### ISSUE TITLE
More than one project

### ISSUE THREAD

**Issue by muuvmuuv** [danielbrodin/atom-project-manager#168]
Hello Im really confused. I tried the hole day to configure more than one project in the project.cson file, but when I press CMD + CTRL + P just the last one come up. How can I save more then one project ?

**Comment by danielbrodin** [comment]
Easiest way to add a project is by having the project open and trigger `Project Manager: Save Project` from the command palette. If you have done it manually my guess is that the format is wrong in `projects.cson`. It should be
```
project1:
  title: "My first project"
  paths: ["project/path"]
project2:
  title: "My second project"
  paths: ["project2/path"]
```
