### ISSUE TITLE
Feature request: Hide folders in the tree view

### ISSUE THREAD

**Issue by tutukin** [danielbrodin/atom-project-manager#187]
It would be nice to hide some folders in the large project.

Given the project structure:

```
/path/to/the/project
  - irrelevant_folder
    -- irrelevant files and folders
  - relevant_folder
    -- relevant files and folders
  - relevant_file.js
```

I want to hide the irrelevant_folder in the tree view.

This would be nice for a large project, where I work only on some files and folders in the root of the project.

PS.
```
// this hides /path/to/the/project/relevant_file.js!
paths: [
  '/path/to/the/project/relevant_folder'
]
```

**Comment by growlsworth** [comment]
+1 
In our project we have multiple apps that all live in one project that we need to bounce around on, but usually not at the same time.

I tried to set up the projec like this:
```coffeescript
myapp:
  title: "myapp"
  paths: [
    # "/work/app/app1"
    # "/work/app/app2"
    # "/work/app/app3"
    "/work/app/app4"
  ]
```
but it didn't like that.

Any support would be greatly appreciated.

**Comment by danielbrodin** [comment]
You could hide the folders using the `core.ignoredNames` setting. 

Otherwise if each folder inside the project is its own project/app you should be able to make a project for each of them
```
one:
  title: "First app"
  paths: ["/work/app/app1"]
two:
  title: "Second app"
  paths: ["/work/app/app2"]
```

**Comment by joaovpmamede** [comment]
@danielbrodin but `core.ignoredNames` is global right?
What would be great is to have something like Project Manager in Sublime:

`"folder_exclude_patterns": ["node_modules", "spec", "tmp", "bin"]`

And these folders would then be ignored by fuzzy-finder.

**Comment by danielbrodin** [comment]
You can override the settings per project using the project manager
```
project:
  title: "My project"
  paths: ["my/path/to/project"]
  settings:
    "core.ignoredNames": ["ignoredThis"]
    "fuzzy-finder.ignoredNames": ["moreIgnore"]
```
There is however an annoying thing in that if you open the settings view it will save the setting globally.

The fuzzy finder is purely based on `core.ignoredNames` and `fuzzy-finder.ignoredNames` so doesn't seem to be an api that let me give it any other paths.

If there is another way i'm up for a pull request.
