### ISSUE TITLE
Allow $HOME in the project path

### ISSUE THREAD

**Issue by jleeothon** [danielbrodin/atom-project-manager#238]
Hi,

I share my atom settings across users accounts / computers though often keep a similar structure (e.g. directories with same names under $HOME). Do you think it would make sense to allow evaluating environment variables in a project's path? E.g.

```
myproject:
  title: "myproject"
  group: "Prjoects"
  template: "general-template"
  paths: [
      "$HOME/myproject"
  ]
```

Thanks!
