### ISSUE TITLE
enable/disable package per project

### ISSUE THREAD

**Issue by qcol** [danielbrodin/atom-project-manager#265]
Hi
It would be very useful if it can be to switch off any packages per project. 
For example: I don't need Codeigniter snippets on Laravel project (and vice versa)

**Comment by dwoutsourcing** [comment]
you can do that. Please read README: https://github.com/danielbrodin/atom-project-manager.

From that page: Settings (object) Enables you to set project specific settings. Everything that goes in the config.cson file can go here. It also supports scoped settings.

**Comment by qcol** [comment]
Doesn't wor for me. I have projects.cson  file like above in project root:

`"*":
  atom:
    core:
      disabledPackages: [
        "codeigniter"
        "activate-power-mode"
      ]
`

**Comment by JustinAiken** [comment]
Try it like this:

```cson
  {
    title: "foo"
    paths: [
      "/your/path"
    ]
    icon: "icon-chevron-right"
    settings:
      core:
        disabledPackages: [ "codeigniter" "activate-power-mode" ] 
    devMode: false
    template: null
  }
```

**Comment by qcol** [comment]
doesn't work too :( 
packages still works on this project 
maybe I don't understand something but I should just place it in the file project.cson in root of my project, right?

**Comment by danielbrodin** [comment]
@qcol if you have it in a local `project.cson` it should be as @JustinAiken wrote but without the root `{}`, so 
```
title: "foo"
paths: [
  "/your/path"
]
icon: "icon-chevron-right"
settings:
  core:
    disabledPackages: [ "codeigniter" "activate-power-mode" ] 
devMode: false
template: null
```
